### ISSUE TITLE
Do you have a musl library that supports UEFI？

### ISSUE THREAD

**Issue by hurryboylqs** [ProjectMile/Mile.Uefi#1]
I want to write an  application under uefi,use msvc as compiler,and I aso porting freetype  ,I found it depend C runtime library.
I did not use edk-libc,because it is so large,my framework is gnuefi.

**Comment by MouriNaruto** [comment]
I don't have a musl libc library that adapts the UEFI enviroment in the current time.
Maybe I can port libc which used by NuttX to this project because I have created this project for discovering stage of porting NuttX to UEFI.
